# Generated by Django 3.2.5 on 2022-05-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Suggestion')),
                ('content', models.TextField(verbose_name='Content')),
                ('is_publishable', models.BooleanField(default=False, verbose_name='Is Publishable ?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at ')),
            ],
            options={
                'verbose_name': 'Suggestion',
                'verbose_name_plural': 'Suggestions',
            },
        ),
    ]
