# Generated by Django 3.2.5 on 2022-05-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
    ]
