# Generated by Django 3.2.5 on 2022-06-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0002_alter_suggestion_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='is_publishable',
            field=models.BooleanField(default=False, verbose_name='Approval Status'),
        ),
    ]
