# Generated by Django 3.2.5 on 2022-05-26 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('status', models.CharField(max_length=30, verbose_name='Operation status')),
                ('item_serviced', models.CharField(max_length=30)),
                ('frequency', models.IntegerField(default=0)),
                ('cost', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Service Ticket',
                'verbose_name_plural': 'Service Tickets',
            },
        ),
    ]
