# Generated by Django 3.2.5 on 2022-06-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceticket',
            name='cost',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='frequency',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
