# Generated by Django 3.2.5 on 2022-06-29 09:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20220629_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceschedule',
            name='id',
        ),
        migrations.AddField(
            model_name='serviceschedule',
            name='ref_no',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='serviceschedule',
            name='service_mark',
            field=models.CharField(choices=[('30000', '30k'), ('60000', '60k'), ('90000', '90k')], default='', max_length=250),
            preserve_default=False,
        ),
    ]
