# Generated by Django 3.2.5 on 2022-05-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_serviceschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceticket',
            name='id',
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='ref_no',
            field=models.CharField(default='44F6B', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
