# Generated by Django 3.2.5 on 2022-05-26 18:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20220526_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceticket',
            name='reference',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
