# Generated by Django 3.2.5 on 2022-05-26 20:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_serviceticket_ref_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceticket',
            name='reference',
            field=models.UUIDField(default=uuid.UUID('3ac55c12-a491-42b4-9fdc-a00c1cac0812'), primary_key=True, serialize=False),
        ),
    ]
