# Generated by Django 3.2.5 on 2022-05-26 20:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_serviceticket_ref_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceticket',
            name='ref_no',
            field=models.UUIDField(default=uuid.UUID('0596d30a-ee70-4dca-a054-1fa830861733'), primary_key=True, serialize=False),
        ),
    ]
