# Generated by Django 3.2.5 on 2022-05-26 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_rename_reference_serviceticket_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceticket',
            old_name='id',
            new_name='ref_no',
        ),
    ]
