# Generated by Django 3.2.5 on 2022-05-31 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0010_rename_id_serviceticket_ref_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceticket',
            name='driver',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
