# Generated by Django 3.2.5 on 2022-06-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_serviceticket_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceticket',
            name='status',
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='approval_status',
            field=models.BooleanField(default=False, verbose_name='Is It Approved ?'),
        ),
    ]
