# Generated by Django 3.2.5 on 2022-06-01 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_auto_20220601_0915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceticket',
            options={'permissions': [('change_service_ticket_status', 'Can change the status of service tickets'), ('close_service_ticket', 'Can remove a service ticket by setting its status as closed')], 'verbose_name': 'Service Ticket', 'verbose_name_plural': 'Service Tickets'},
        ),
    ]
