# Generated by Django 3.2.5 on 2022-06-02 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=30, verbose_name='Plate Number')),
                ('make', models.CharField(max_length=30, verbose_name='Make')),
                ('model', models.CharField(max_length=30, verbose_name='Vehicle Model')),
                ('category', models.CharField(max_length=30, verbose_name='Category')),
                ('status', models.CharField(max_length=30, verbose_name='Operation status')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ('plate_number', 'driver', 'make', 'model', 'category', 'status'),
            },
        ),
    ]
