# Generated by Django 3.2.5 on 2022-06-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(help_text='Enter plate number of the vehicle', max_length=30, verbose_name='Plate Number'),
        ),
    ]
