# Generated by Django 3.2.5 on 2022-06-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_auto_20220629_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='category',
            field=models.CharField(choices=[('bus', 'bus'), ('car', 'car'), ('lory', 'lory')], max_length=30, verbose_name='Category'),
        ),
    ]
